# Generated by Django 6.0.5 on 2026-05-07 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_order', '0001_initial'),
        ('restaurants', '0002_menuitem_ingredients_restaurant_closing_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='grouporder',
            name='invite_code',
            field=models.CharField(blank=True, max_length=8, unique=True),
        ),
        migrations.AddField(
            model_name='grouporder',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant'),
        ),
        migrations.AlterField(
            model_name='grouporder',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='group_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='grouporder',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='grouporderitem',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_items', to='group_order.grouporder'),
        ),
        migrations.AlterField(
            model_name='grouporderitem',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.menuitem'),
        ),
        migrations.AlterField(
            model_name='grouporderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
