# Generated by Django 6.0.5 on 2026-05-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_order', '0002_grouporder_invite_code_grouporder_restaurant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouporderitem',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('BKASH', 'Bkash'), ('NAGAD', 'Nagad')], default='COD', max_length=10),
        ),
    ]
