# Generated by Django 6.0.5 on 2026-05-14 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_order', '0004_groupmemberpayment'),
        ('orders', '0005_alter_order_status_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouporder',
            name='main_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_order', to='orders.order'),
        ),
    ]
